// QC-mode data access. The web WRITES only these two tables (qc_operators,
// qc_reviews); captures/capture_files stay desktop-owned and are read-only here.
// Shares the single pg pool from capture-db (which also registers the int8 parser).
import { getPool } from "./capture-db";
import type {
  CaptureWithReview,
  Grade,
  PackageDaySummary,
  QcOperator,
  QcReview,
  QcReviewInput,
} from "./types";

/** Thrown when a review targets a capture_id that does not exist (FK 23503). */
export class QcNotFoundError extends Error {}

function isoOrNull(d: Date | string | null | undefined): string {
  if (d == null) return "";
  if (typeof d === "string") return d;
  return d.toISOString();
}

// ---------------- operators ----------------

export async function findOperator(badge: string): Promise<QcOperator | null> {
  const r = await getPool().query<{
    badge_number: string;
    full_name: string;
    active: boolean;
    created_at: Date;
  }>(
    `SELECT badge_number, full_name, active, created_at
     FROM qc_operators
     WHERE badge_number = $1 AND active = TRUE`,
    [badge],
  );
  const row = r.rows[0];
  if (!row) return null;
  return { ...row, created_at: isoOrNull(row.created_at) };
}

/**
 * Register a NEW operator. Never overwrites an existing badge — re-registering
 * is a no-op (created=false), so the public register page cannot rename or
 * re-activate someone else's badge. Name fixes / re-activation are a DBA action.
 */
export async function registerOperator(
  badge: string,
  fullName: string,
): Promise<{ created: boolean }> {
  const r = await getPool().query(
    `INSERT INTO qc_operators (badge_number, full_name, active, created_at)
     VALUES ($1, $2, TRUE, $3)
     ON CONFLICT (badge_number) DO NOTHING`,
    [badge, fullName, new Date()],
  );
  return { created: (r.rowCount ?? 0) > 0 };
}

/** Log that an operator accepted the Visual Aid QC criteria (audit trail). */
export async function recordAcknowledgement(badge: string): Promise<void> {
  await getPool().query(
    `INSERT INTO qc_acknowledgements (badge_number, accepted_at) VALUES ($1, $2)`,
    [badge, new Date()],
  );
}

// ---------------- reviews ----------------

const REVIEW_COLS = `id, capture_id, badge_number, reviewed_at,
  ball_size, ball_size_note, pad_bond, pad_bond_note,
  weld_damage, weld_damage_note, overall_verdict`;

interface ReviewRow {
  id: number;
  capture_id: string;
  badge_number: string;
  reviewed_at: Date | string;
  ball_size: Grade;
  ball_size_note: string | null;
  pad_bond: Grade;
  pad_bond_note: string | null;
  weld_damage: Grade;
  weld_damage_note: string | null;
  overall_verdict: Grade;
}

function rowToReview(r: ReviewRow): QcReview {
  return {
    id: r.id,
    capture_id: r.capture_id,
    badge_number: r.badge_number,
    reviewed_at: isoOrNull(r.reviewed_at),
    ball_size: r.ball_size,
    ball_size_note: r.ball_size_note,
    pad_bond: r.pad_bond,
    pad_bond_note: r.pad_bond_note,
    weld_damage: r.weld_damage,
    weld_damage_note: r.weld_damage_note,
    overall_verdict: r.overall_verdict,
  };
}

export async function getReview(captureId: string): Promise<QcReview | null> {
  const r = await getPool().query<ReviewRow>(
    `SELECT ${REVIEW_COLS} FROM qc_reviews WHERE capture_id = $1`,
    [captureId],
  );
  return r.rows[0] ? rowToReview(r.rows[0]) : null;
}

/**
 * UPSERT the current verdict for a capture (re-grade overwrites). The capture
 * FK enforces existence — a missing capture surfaces as QcNotFoundError.
 * overall_verdict is generated by the DB, never sent from the client.
 * `badge` comes from the session cookie, never the request body.
 */
export async function submitReview(
  badge: string,
  captureId: string,
  input: QcReviewInput,
): Promise<QcReview> {
  try {
    const r = await getPool().query<ReviewRow>(
      `INSERT INTO qc_reviews (
         capture_id, badge_number, reviewed_at,
         ball_size, ball_size_note, pad_bond, pad_bond_note, weld_damage, weld_damage_note
       ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
       ON CONFLICT (capture_id) DO UPDATE SET
         badge_number = EXCLUDED.badge_number, reviewed_at = EXCLUDED.reviewed_at,
         ball_size = EXCLUDED.ball_size, ball_size_note = EXCLUDED.ball_size_note,
         pad_bond = EXCLUDED.pad_bond, pad_bond_note = EXCLUDED.pad_bond_note,
         weld_damage = EXCLUDED.weld_damage, weld_damage_note = EXCLUDED.weld_damage_note
       RETURNING ${REVIEW_COLS}`,
      [
        captureId, badge, new Date(),
        input.ball_size, input.ball_size_note,
        input.pad_bond, input.pad_bond_note,
        input.weld_damage, input.weld_damage_note,
      ],
    );
    return rowToReview(r.rows[0]);
  } catch (e) {
    if ((e as { code?: string })?.code === "23503") {
      throw new QcNotFoundError(`capture ${captureId} not found`);
    }
    throw e;
  }
}

// ---------------- queue ----------------

export interface QueueFilter {
  since?: Date | null;
  until?: Date | null;
  package?: string | null;
  status?: "pending" | "reviewed" | "all";
  limit?: number;
  offset?: number;
}

interface QueueRow {
  capture_id: string;
  confirmed_at: Date | string;
  lot_id: string;
  bonding_number: string | null;
  lot_location: string | null;
  mpc: string | null;
  package: string | null;
  qs: string | null;
  operator_badge: string;
  hostname: string | null;
  app_version: string | null;
  mode: string;
  raw_lot_info: Record<string, unknown> | string | null;
  slot: string | null;
  fused_path: string | null;
  fused_name: string | null;
  file_size_bytes: number | null;
  file_sha256: string | null;
  r_id: number | null;
  r_badge: string | null;
  r_reviewed_at: Date | string | null;
  ball_size: Grade | null;
  ball_size_note: string | null;
  pad_bond: Grade | null;
  pad_bond_note: string | null;
  weld_damage: Grade | null;
  weld_damage_note: string | null;
  overall_verdict: Grade | null;
}

/** Captures (newest first) within the window, each with its current review (or
 * null). Mirrors recentCaptures' paged-CTE + file-join + in-memory grouping. */
export async function reviewQueue(
  f: QueueFilter = {},
): Promise<CaptureWithReview[]> {
  const limit = f.limit ?? 60;
  const offset = f.offset ?? 0;
  const status = f.status ?? "pending";

  const params: unknown[] = [];
  const clauses: string[] = [];
  if (f.since) {
    params.push(f.since);
    clauses.push(`c.confirmed_at >= $${params.length}`);
  }
  if (f.until) {
    params.push(f.until);
    clauses.push(`c.confirmed_at < $${params.length}`);
  }
  if (f.package != null) {
    params.push(f.package);
    clauses.push(`COALESCE(c.package, '') = $${params.length}`);
  }
  if (status === "pending") clauses.push(`r.id IS NULL`);
  else if (status === "reviewed") clauses.push(`r.id IS NOT NULL`);
  const where = clauses.length ? `WHERE ${clauses.join(" AND ")}` : "";

  params.push(limit);
  const limIdx = params.length;
  params.push(offset);
  const offIdx = params.length;

  const sql = `
    WITH paged AS (
      SELECT c.capture_id, c.confirmed_at
      FROM captures c
      LEFT JOIN qc_reviews r ON r.capture_id = c.capture_id
      ${where}
      ORDER BY c.confirmed_at DESC, c.capture_id
      LIMIT $${limIdx} OFFSET $${offIdx}
    )
    SELECT c.*,
           f.slot, f.fused_path, f.fused_name,
           f.size_bytes AS file_size_bytes, f.sha256 AS file_sha256,
           r.id AS r_id, r.badge_number AS r_badge, r.reviewed_at AS r_reviewed_at,
           r.ball_size, r.ball_size_note, r.pad_bond, r.pad_bond_note,
           r.weld_damage, r.weld_damage_note, r.overall_verdict
    FROM captures c
    INNER JOIN paged p ON p.capture_id = c.capture_id
    LEFT JOIN capture_files f ON f.capture_id = c.capture_id
    LEFT JOIN qc_reviews r ON r.capture_id = c.capture_id
    ORDER BY c.confirmed_at DESC, c.capture_id, f.id
  `;
  const result = await getPool().query<QueueRow>(sql, params);

  const grouped = new Map<string, CaptureWithReview>();
  const order: string[] = [];
  for (const r of result.rows) {
    let cap = grouped.get(r.capture_id);
    if (!cap) {
      cap = {
        capture_id: r.capture_id,
        confirmed_at: isoOrNull(r.confirmed_at),
        lot_id: r.lot_id,
        bonding_number: r.bonding_number,
        lot_location: r.lot_location,
        mpc: r.mpc,
        package: r.package,
        qs: r.qs,
        operator_badge: r.operator_badge,
        hostname: r.hostname,
        app_version: r.app_version,
        mode: r.mode,
        raw_lot_info: r.raw_lot_info,
        files: [],
        review: r.r_id == null ? null : {
          id: r.r_id,
          capture_id: r.capture_id,
          badge_number: r.r_badge as string,
          reviewed_at: isoOrNull(r.r_reviewed_at),
          ball_size: r.ball_size as Grade,
          ball_size_note: r.ball_size_note,
          pad_bond: r.pad_bond as Grade,
          pad_bond_note: r.pad_bond_note,
          weld_damage: r.weld_damage as Grade,
          weld_damage_note: r.weld_damage_note,
          overall_verdict: r.overall_verdict as Grade,
        },
      };
      grouped.set(r.capture_id, cap);
      order.push(r.capture_id);
    }
    if (r.slot != null && r.fused_path != null && r.fused_name != null) {
      cap.files.push({
        slot: r.slot,
        fused_path: r.fused_path,
        fused_name: r.fused_name,
        size_bytes: r.file_size_bytes,
        sha256: r.file_sha256,
      });
    }
  }
  return order.map((id) => grouped.get(id)!);
}

/** Pending / reviewed / total capture counts for the same window the queue uses. */
export async function queueCounts(f: {
  since?: Date | null;
  until?: Date | null;
  package?: string | null;
}): Promise<{ pending: number; reviewed: number; total: number }> {
  const params: unknown[] = [];
  const clauses: string[] = [];
  if (f.since) {
    params.push(f.since);
    clauses.push(`c.confirmed_at >= $${params.length}`);
  }
  if (f.until) {
    params.push(f.until);
    clauses.push(`c.confirmed_at < $${params.length}`);
  }
  if (f.package != null) {
    params.push(f.package);
    clauses.push(`COALESCE(c.package, '') = $${params.length}`);
  }
  const where = clauses.length ? `WHERE ${clauses.join(" AND ")}` : "";
  const r = await getPool().query<{
    pending: number;
    reviewed: number;
    total: number;
  }>(
    `SELECT
       COUNT(*) FILTER (WHERE r.id IS NULL)::int     AS pending,
       COUNT(*) FILTER (WHERE r.id IS NOT NULL)::int AS reviewed,
       COUNT(*)::int                                 AS total
     FROM captures c
     LEFT JOIN qc_reviews r ON r.capture_id = c.capture_id
     ${where}`,
    params,
  );
  return r.rows[0] ?? { pending: 0, reviewed: 0, total: 0 };
}

// ---------------- summary ----------------

/**
 * Per-package coverage for one calendar day (bonded that day): how many of the
 * day's captures have been QC-reviewed (pass/reject), out of the total bonded.
 * Keyed on captures.confirmed_at (production day). Day bounds are built by the
 * caller in Node-local time (the web must run in the plant timezone).
 */
export async function dailyPackageSummary(
  dayStart: Date,
  nextDay: Date,
): Promise<PackageDaySummary[]> {
  const r = await getPool().query<PackageDaySummary>(
    `SELECT
       COALESCE(c.package, '(no package)')                       AS package,
       COUNT(*)::int                                             AS total_captures,
       COUNT(r.id)::int                                          AS reviewed,
       COUNT(*) FILTER (WHERE r.overall_verdict = 'PASS')::int   AS pass,
       COUNT(*) FILTER (WHERE r.overall_verdict = 'REJECT')::int AS reject
     FROM captures c
     LEFT JOIN qc_reviews r ON r.capture_id = c.capture_id
     WHERE c.confirmed_at >= $1 AND c.confirmed_at < $2
     GROUP BY COALESCE(c.package, '(no package)')
     ORDER BY total_captures DESC, package`,
    [dayStart, nextDay],
  );
  return r.rows;
}

/** Current QC verdict + reviewer badge for a set of captures (only those that
 * have a review). Used by the read-only dashboard to badge each card. */
export async function reviewStatusFor(
  captureIds: string[],
): Promise<Record<string, { verdict: Grade; badge: string }>> {
  if (captureIds.length === 0) return {};
  const r = await getPool().query<{
    capture_id: string;
    overall_verdict: Grade;
    badge_number: string;
  }>(
    `SELECT capture_id, overall_verdict, badge_number
     FROM qc_reviews
     WHERE capture_id = ANY($1::uuid[])`,
    [captureIds],
  );
  const map: Record<string, { verdict: Grade; badge: string }> = {};
  for (const row of r.rows) {
    map[row.capture_id] = { verdict: row.overall_verdict, badge: row.badge_number };
  }
  return map;
}
