export type Mode = "mode1" | "mode2";

export interface CaptureFile {
  slot: string;
  fused_path: string;
  fused_name: string;
  size_bytes: number | null;
  sha256: string | null;
  image_rel?: string | null;
}

export interface Capture {
  capture_id: string;
  confirmed_at: string;
  lot_id: string;
  bonding_number: string | null;
  lot_location: string | null;
  mpc: string | null;
  package: string | null;
  qs: string | null;
  operator_badge: string;
  hostname: string | null;
  app_version: string | null;
  mode: string;
  raw_lot_info: Record<string, unknown> | string | null;
  files: CaptureFile[];
}

export interface LotSummary {
  lot_id: string;
  last_confirmed_at: string;
  capture_count: number;
}

export interface CaptureFilter {
  since?: Date | null;
  until?: Date | null;
  bonding_number?: string | null;
  lot_location?: string | null;
  lot_id?: string | null;
  mode?: Mode | null;
  limit?: number;
  offset?: number;
}

export interface BucketCounts {
  today: number;
  week: number;
  month: number;
  total: number;
}

// ---------------- QC mode ----------------

export type Grade = "PASS" | "REJECT";

/** QC state shown on a capture card: graded PASS/REJECT, or AWAITING review. */
export type QcStatus = Grade | "AWAITING";

export interface QcOperator {
  badge_number: string;
  full_name: string;
  active: boolean;
  created_at: string;
}

/** The three graded items submitted from the review form. */
export interface QcReviewInput {
  ball_size: Grade;
  ball_size_note: string | null;
  pad_bond: Grade;
  pad_bond_note: string | null;
  weld_damage: Grade;
  weld_damage_note: string | null;
}

export interface QcReview extends QcReviewInput {
  id: number;
  capture_id: string;
  badge_number: string;
  reviewed_at: string;
  overall_verdict: Grade; // generated by the DB from the three items
}

/** A capture plus its current QC review (null = still needs review). */
export interface CaptureWithReview extends Capture {
  review: QcReview | null;
}

/** Per-package daily QC coverage: how many of the day's captures are reviewed
 * (pass/reject), out of the total bonded that day. */
export interface PackageDaySummary {
  package: string;
  total_captures: number;
  reviewed: number;
  pass: number;
  reject: number;
}
